import requests
import gzip
import shutil


# Tải tệp knn_model.pkl.gz từ GitHub (hoặc bạn có thể tải nó từ một URL nếu cần)
url = "https://github.com/anha254/Reccomender-system/raw/master/knn_model.pkl.gz"
r = requests.get(url)
with open("knn_model.pkl.gz", "wb") as f:
    f.write(r.content)

# Giải nén tệp knn_model.pkl.gz
with gzip.open("knn_model.pkl.gz", "rb") as f_in:
    with open("knn_model.pkl", "wb") as f_out:
        shutil.copyfileobj(f_in, f_out)

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest
